#!/usr/bin/env python3
"""Transcribe the large constant tables of RFC 6386 into src/tables_rfc.rs.

The tables are data (probabilities and quantiser steps), printed in the
RFC's normative prose sections 11.5, 13.4, 13.5 and 14.1. This script reads
the RFC's plain text (https://www.rfc-editor.org/rfc/rfc6386.txt), finds each
table by its declaration, and copies its numbers in order -- so the Rust
tables are a mechanical transcription that can be re-checked at any time:

    curl -o rfc6386.txt https://www.rfc-editor.org/rfc/rfc6386.txt
    python3 tools/tables_from_rfc.py rfc6386.txt > src/tables_rfc.rs

Only text before section 20 (the reference decoder's source listings) is
read.
"""
import re
import sys


def body(text):
    end = text.index("\n20.  Attachment One: Reference Decoder Source Code\n\n20.1.")
    return text[:end]


def numbers_after(text, decl, count):
    start = text.index(decl)
    eq = text.index("=", start)
    out = []
    pos = eq + 1
    # Skip page headers/footers the RFC inserts between table rows.
    for line in text[pos:].splitlines():
        if line.startswith("RFC 6386") or line.startswith("Bankoski"):
            continue
        out.extend(int(n) for n in re.findall(r"-?\d+", line))
        if len(out) >= count:
            break
    if len(out) != count:
        raise SystemExit(f"{decl}: found {len(out)} numbers, wanted {count}")
    return out


def nest(vals, dims):
    if len(dims) == 1:
        return "[" + ", ".join(str(v) for v in vals) + "]"
    step = len(vals) // dims[0]
    return "[" + ", ".join(nest(vals[i * step:(i + 1) * step], dims[1:]) for i in range(dims[0])) + "]"


def emit(name, ty, vals, dims, doc):
    print(f"/// {doc}")
    print(f"pub(crate) static {name}: {ty} = {nest(vals, dims)};")
    print()


def main():
    text = body(open(sys.argv[1], encoding="utf-8").read())
    print("// Generated by tools/tables_from_rfc.py from the text of RFC 6386; do not edit.")
    print("// Run `cargo fmt` after regenerating.")
    print()
    emit("KF_BMODE_PROBS", "[[[u8; 9]; 10]; 10]",
         numbers_after(text, "const Prob kf_bmode_prob [num_intra_bmodes] [num_intra_bmodes]\n     [num_intra_bmodes-1] =", 900),
         [10, 10, 9], "Key-frame subblock mode probabilities, `[above][left][node]` (RFC 6386 section 11.5).")
    emit("COEFF_UPDATE_PROBS", "[[[[u8; 11]; 3]; 8]; 4]",
         numbers_after(text, "const Prob coeff_update_probs [4] [8] [3] [num_dct_tokens-1] =", 1056),
         [4, 8, 3, 11], "Probabilities that each token probability is updated (RFC 6386 section 13.4).")
    emit("DEFAULT_COEFF_PROBS", "[[[[u8; 11]; 3]; 8]; 4]",
         numbers_after(text, "const Prob default_coeff_probs [4] [8] [3] [num_dct_tokens - 1] =", 1056),
         [4, 8, 3, 11], "Default token probabilities, restored on every key frame (RFC 6386 section 13.5).")
    emit("DC_QLOOKUP", "[u16; 128]",
         numbers_after(text, "static const int dc_qlookup[QINDEX_RANGE] =", 128),
         [128], "DC dequantisation factors by quantiser index (RFC 6386 section 14.1).")
    emit("AC_QLOOKUP", "[u16; 128]",
         numbers_after(text, "static const int ac_qlookup[QINDEX_RANGE] =", 128),
         [128], "AC dequantisation factors by quantiser index (RFC 6386 section 14.1).")


if __name__ == "__main__":
    main()
